### ISSUE TITLE
MacOS stat command differs from linux

### ISSUE THREAD

**Issue by CygnusHyoga** [Lanchon/ddwrt-autoupdate#6]
MacOS and Linux stat command differs from each other respect the printf argument:

Linux: stat --printf '%s'
MacOS: stat -f '%z'

I've problem with the part of the script that use the stat command:
```
# Ensure firmware is at least 1 MiB in size:
(( "$(stat --printf '%s' "$local_firmware_file")" >= (1 * 1024 * 1024) )) || error "Firmware size check failed"
```

Error:
```
air:ddwrt-autoupdate kulo4$ stat --printf %s r41586-20191121-netgear-r9000-webflash.bin
stat: illegal option -- -
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
```

Example stat command in macOS :
```
air:ddwrt-autoupdate kulo4$ stat -f '%z' repos/netgear-r9000/.tmp/r41586-20191121-netgear-r9000-webflash.bin 
415
air:ddwrt-autoupdate kulo4$ 
```

**Comment by Lanchon** [comment]
in general i'm aware of these issues. i'm not interested in supporting proprietary OS'es. i'm especially against having anything to do with anything done by apple, much more so than microsoft.

you are very welcome to fork, but pull requests for macOS won't be merged, sorry,

**Comment by Lanchon** [comment]
in the readme, the requirements section states:

-  A Linux box with network access to the DD-WRT device(s).

other OS'es are not supported, so i'll close this.
thanks for understanding.
